Repository KU-Yacht/Yacht, pull requests merged in 2024-11, with the labels that each got.

#30 fix: fix dependency name
  argo-workflows/template-real.yaml
Labels: 🛠️Infra

#32 fix: add parameter to clone-cdk8s stage in workflow
  argo-workflows/template-real.yaml
Labels: 🛠️Infra

#33 feat: Delegate ingress generation to cdk8s
  argo-workflows/template-real.yaml
  cdk8s/backend/main.ts
Labels: 🛠️Infra

#35 feat: add variable application options
  argo-events/create-repo-sensor.yaml
  argo-workflows/template-real.yaml
  cdk8s/backend/main.ts
Labels: 🛠️Infra

#36 feat: add role of workflow result
  argo-events/rbac.yaml
Labels: 🛠️Infra

#37 fix: Set backticks to apply variables
  cdk8s/backend/main.ts
Labels: 🛠️Infra, 🐛bug fix

#38 fix: Convert port and replica count to int
  cdk8s/backend/main.ts
Labels: 🛠️Infra, 🐛bug fix

#39 feat: add app_name parameter to file path in make-deploy stage
  argo-workflows/template-real.yaml
Labels: 🛠️Infra

#40 feat: add workflowId Post stage
  argo-events/create-repo-sensor.yaml
  argo-workflows/template-real.yaml
Labels: 🛠️Infra

#41 feat: add ttl to workflow stage
  argo-workflows/template-real.yaml
Labels: 🛠️Infra

#42 feat: add notify backend step to argo event sensor
  argo-events/create-repo-sensor.yaml
Labels: 🛠️Infra

#43 Backend merge
  .github/workflows/.DS_Store
  .gitignore
  back-end/src/main/java/site/yacht/backend/BackendApplication.java
  back-end/src/main/java/site/yacht/backend/domain/application/api/ApplicationApi.java
  back-end/src/main/java/site/yacht/backend/domain/application/api/request/ApplicationRegisterRequest.java
  back-end/src/main/java/site/yacht/backend/domain/application/api/response/FindApplicationDetailResponse.java
  back-end/src/main/java/site/yacht/backend/domain/application/domain/Application.java
  back-end/src/main/java/site/yacht/backend/domain/application/dto/ApplicationRegisterDto.java
  back-end/src/main/java/site/yacht/backend/domain/application/service/ApplicationService.java
  back-end/src/main/java/site/yacht/backend/domain/deployment/api/DeploymentApi.java
  back-end/src/main/java/site/yacht/backend/domain/deployment/api/response/DeployDetailResponse.java
  back-end/src/main/java/site/yacht/backend/domain/deployment/api/response/DeployResponse.java
  back-end/src/main/java/site/yacht/backend/domain/deployment/dto/DeployApplicationRequestToCloud.java
  back-end/src/main/java/site/yacht/backend/domain/deployment/service/DeployService.java
  back-end/src/main/java/site/yacht/backend/domain/deployment_history/api/DeploymentHistoryApi.java
  back-end/src/main/java/site/yacht/backend/domain/deployment_history/api/request/DeploymentHistorySaveRequest.java
  back-end/src/main/java/site/yacht/backend/domain/deployment_history/repository/DeploymentHistoryRepository.java
  back-end/src/main/java/site/yacht/backend/domain/project/api/ProjectController.java
  back-end/src/main/java/site/yacht/backend/domain/project/api/response/FindProjectListResponse.java
  back-end/src/main/java/site/yacht/backend/global/config/SwaggerConfig.java
  back-end/src/main/java/site/yacht/backend/global/config/WebSecurityConfig.java
  back-end/src/main/java/site/yacht/backend/global/config/swagger/BearerTokenProperties.java
  back-end/src/main/java/site/yacht/backend/global/config/swagger/ServerProperties.java
  back-end/src/main/java/site/yacht/backend/global/config/swagger/SwaggerConfig.java
Labels: ⚙️ Back-End
